language: python
python: 3.5
env: # These should match the tox env list
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=pypy
install: pip install coveralls tox
script: tox
after_success:
    - coveralls
sudo: false
